### ISSUE TITLE
Run unittest failed

### ISSUE THREAD

**Issue by henaiguo** [wqking/eventpp#57]
## Runtime environment  
ubuntu 22.04
gcc 11.3
Catch v2.13.9
## Building process  
```
cd xxx/eventpp/tests/build
cmake ..
make linux
cd unittest
make
./unittest
```
## Result
![image](https://user-images.githubusercontent.com/14122312/223903294-357e0770-e711-40bb-bc90-3633900839f0.png)  

**After I commented out all `test_callbacklist_multithread.cpp`, the unittest passed.**

**Comment by wqking** [comment]
Thanks for the bug report. It's a racing condition in newly added function `CallbackListBase::ownsHandle`. I've fixed it.  
Note: `ownsHandle` is called in `assert` which is only available in debug mode. So this bug can only be reproduced in debug mode, not release mode in which `assert` is gone.

**Comment by henaiguo** [comment]
OK, I see. But, *unittest* still failed to run.  it seems to be a deadlock  

![image](https://user-images.githubusercontent.com/14122312/224204724-6e6eeaa2-f41c-40a8-8d1e-93fe781e1066.png)

***This is the result of pressing ctrl+c after waiting for a while***

**Comment by wqking** [comment]
No, it's not dead lock, it's just super slow in debug mode. In debug mode, in `CallbackList::remove`, there is an assertion that iterates the whole list, which has 1M items in that test. That results 1M*1M checks and never finish. I'm thinking of removing the assertion.

**Comment by wqking** [comment]
I removed the assertion, the unit tests should not be very slow even in debug mode.
